# Generated by Django 4.2.5 on 2025-04-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamestats',
            name='ice_time_minutes',
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('F', 'Forward'), ('D', 'Defense'), ('G', 'Goalie')], max_length=1),
        ),
    ]
