# Generated by Django 5.0 on 2025-04-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_remove_playergamestats_ice_time_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.CharField(choices=[('A', 'Away'), ('H', 'Home')], default='H', max_length=1),
        ),
    ]
